# Generated by Django 3.2 on 2021-07-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysProdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.IntegerField(unique=True)),
                ('produce', models.IntegerField(default=0)),
                ('reject', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
