# Generated by Django 3.2 on 2021-07-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_todaysproddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaysproddata',
            name='name_id',
            field=models.IntegerField(),
        ),
    ]
