# Generated by Django 3.2 on 2021-07-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_todaysproddata_name_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instockqty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.IntegerField()),
                ('produceqty', models.IntegerField(default=0)),
                ('rejectqty', models.IntegerField(default=0)),
            ],
        ),
    ]
