# Generated by Django 3.2 on 2021-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_instockqty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totalselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.IntegerField()),
                ('sellqty', models.IntegerField()),
                ('sellingprice', models.IntegerField()),
                ('totalprofit', models.IntegerField()),
                ('selldate', models.DateField()),
            ],
        ),
    ]
