# Generated by Django 3.2 on 2021-07-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_totalselling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturingprice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.IntegerField()),
                ('manucost', models.IntegerField()),
            ],
        ),
    ]
