# Generated by Django 3.2 on 2021-07-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_manufacturingprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalselling',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
