# Generated by Django 3.2 on 2021-07-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_totalselling_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturingprice',
            old_name='name_id',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rawmaterialdata',
            old_name='name',
            new_name='name_id',
        ),
    ]
