# Generated by Django 3.2 on 2021-07-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20210718_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingprice',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rawmaterialdata',
            name='name_id',
            field=models.IntegerField(),
        ),
    ]
