# Generated by Django 3.2 on 2021-07-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20210718_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingprice',
            name='disc',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
