# Generated by Django 3.2 on 2021-07-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_manufacturingprice_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialdata',
            name='totalInvest',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rawmaterialdata',
            name='totalqty',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rawmaterialdata',
            name='rawqty',
            field=models.BigIntegerField(default=0),
        ),
    ]
